CREATE TABLE [dbo].[Tasks]
(
	[Id] INT NOT NULL IDENTITY(1, 1),
	[Title] VARCHAR(256) NOT NULL DEFAULT '',
	[Description] TEXT NOT NULL,		
	[DueOn] DATETIME NULL,
	[IsCompleted] BIT NOT NULL,
	[CompletedAt] DATETIME NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[UpdatedAt] DATETIME NOT NULL DEFAULT GETUTCDATE(), 
    [Version] ROWVERSION NOT NULL, 
	CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED ([Id] ASC)
)
GO

CREATE INDEX [IX_Tasks_IsCompleted] ON [dbo].[Tasks] ([IsCompleted])
GO
